module.exports = {
  STATE_CONNECTED: "CONNECTED",
  STATE_DISCONNECTED: "DISCONNECTED",
  STATUS_ERROR: "error",
  STATUS_SUCESSFULLY: "sucessfully",
  MESSAGE_ORIGIN_IA: "IA", //ENVIADO PELA IA - USUARO ACTUAL
  MESSAGE_ORIGIN_TO: "POTENTIAL_CLIENT" // ENVIADO PELO CLIENTE - QUEM ESTA A CONVERSAR COM O USUARIO ACTUAL
};
